name: SlimefunLuckyBlocks
version: 1.1
api-version: 1.13
author: mrCookieSlime
website: http://dev.bukkit.org/profiles/mrCookieSlime/bukkit-plugins/

main: me.mrCookieSlime.SlimefunLuckyBlocks.SlimefunLuckyBlocks

depend: [Slimefun, CS-CoreLib]
